name: Build dylib only

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build
        run: |
          export THEOS=$HOME/theos
          make clean
          make

      - name: Extract ONLY dylib
        run: |
          mkdir -p output
          find . -name "*.dylib" | head -n 1 | xargs -I{} cp {} output/MostashClicker.dylib

      - name: Upload ONLY file
        uses: actions/upload-artifact@v4
        with:
          name: MostashClicker
          path: output/MostashClicker.dylib
