name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build tweak
        uses: Randomblock1/theos-action@v1

      - name: Find ONLY dylib
        run: |
          mkdir -p output

          # أخذ أول dylib فقط (الملف النهائي)
          FILE=$(find . -name "*.dylib" | head -n 1)

          echo "Found dylib: $FILE"

          cp "$FILE" output/MostashClicker.dylib

          ls -lah output

      - name: Upload ONLY dylib
        uses: actions/upload-artifact@v4
        with:
          name: MostashClicker-dylib
          path: output/MostashClicker.dylib
